title: Jardeson Barbosa
logo: "/images/logo.png?raw=true"
description:
  Bookmark this to follow my project updates
  <br><br>
  <a href="https://www.linkedin.com/in/jardesonbarbosa/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: G-KLCWDLXQGK
